version: '3.6'
services:
  app:
    build: .
    restart: always
    volumes:
          - ./:/usr/src/app
    environment:
      ELASTICSEARCH_HOST_IP: elasticsearch
      INDEX_NAME: winter_products
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    ports:
      - 5000:5000
  elasticsearch:
    image: "elasticsearch:7.5.1"
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"